#!/usr/bin/env node
import { access, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { basename, join, resolve } from "node:path";

const EMIT_MARKER = "# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---";

interface CliOptions {
  targetRepo: string;
  prefix?: string;
  apply: boolean;
}

interface HookMapping {
  eventType: string;
}

interface HookCommand {
  type?: unknown;
  bash?: unknown;
  [key: string]: unknown;
}

interface EmitStripResult {
  updated: string;
  removedBlocks: number;
}

interface ManifestRevertResult {
  updated: Record<string, unknown>;
  removedEvents: string[];
  changed: boolean;
}

const HOOK_MAP: Record<string, HookMapping> = {
  "session-start.sh": { eventType: "sessionStart" },
  "sessionstart.sh": { eventType: "sessionStart" },
  "session-end.sh": { eventType: "sessionEnd" },
  "sessionend.sh": { eventType: "sessionEnd" },
  "subagent-stop.sh": { eventType: "subagentStop" },
  "subagent-start.sh": { eventType: "subagentStart" },
  "log-prompt.sh": { eventType: "userPromptSubmitted" },
  "pre-tool-use.sh": { eventType: "preToolUse" },
  "post-tool-use.sh": { eventType: "postToolUse" },
  "post-tool-use-failure.sh": { eventType: "postToolUseFailure" },
  "agent-stop.sh": { eventType: "agentStop" },
  "notification.sh": { eventType: "notification" },
  "error-occurred.sh": { eventType: "errorOccurred" },
};

const CANONICAL_HOOK_NAMES = (() => {
  const eventSeen = new Set<string>();
  const hyphenated = Object.keys(HOOK_MAP).filter((name) => name.includes("-"));
  const nonHyphenated = Object.keys(HOOK_MAP).filter((name) => !name.includes("-"));

  const result: string[] = [];
  for (const name of hyphenated) {
    const eventType = HOOK_MAP[name].eventType;
    if (!eventSeen.has(eventType)) {
      eventSeen.add(eventType);
      result.push(name);
    }
  }
  for (const name of nonHyphenated) {
    const eventType = HOOK_MAP[name].eventType;
    if (!eventSeen.has(eventType)) {
      eventSeen.add(eventType);
      result.push(name);
    }
  }
  return result;
})();

const EVENT_TO_CANONICAL_HOOK: Record<string, string> = CANONICAL_HOOK_NAMES.reduce<Record<string, string>>((acc, hookName) => {
  acc[HOOK_MAP[hookName].eventType] = hookName;
  return acc;
}, {});

/**
 * Name of the dedicated visualizer hook manifest created by bootstrap.
 */
const VISUALIZER_MANIFEST_NAME = "visualizer-hooks.json";

const STUB_SCRIPT_LINES = [
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  "# Stub hook generated by bootstrap-existing-repo.",
  "# Add your custom logic above the visualizer emit block below.",
  "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
  "REPO_ROOT=\"$(cd \"$SCRIPT_DIR/../..\" && pwd)\"",
  "exit 0",
] as const;

function fail(message: string): never {
  console.error(`unbootstrap-existing-repo error: ${message}`);
  process.exit(1);
}

function usage(): string {
  return [
    "Usage:",
    "  npm run unbootstrap:repo -- /absolute/path/to/target-repo [options]",
    "",
    "Options:",
    "  --apply            Apply changes (default is dry-run)",
    "  --prefix <name>    Prefix used during bootstrap (e.g. viz)",
    "  -h, --help         Show this help",
    "",
    "Dry-run mode prints planned removals without changing files.",
  ].join("\n");
}

function parseCliArgs(argv: string[]): CliOptions | null {
  const positional: string[] = [];
  let prefix: string | undefined;
  let apply = false;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--prefix") {
      const value = argv[i + 1];
      if (!value || value.startsWith("--")) {
        fail("--prefix requires a value (e.g. --prefix viz)");
      }
      prefix = value;
      i += 1;
    } else if (arg === "--apply") {
      apply = true;
    } else if (arg === "-h" || arg === "--help") {
      console.log(usage());
      process.exit(0);
    } else if (!arg.startsWith("--")) {
      positional.push(arg);
    }
  }

  if (positional.length === 0) {
    return null;
  }

  return { targetRepo: positional[0], prefix, apply };
}

async function ensureExists(path: string): Promise<void> {
  try {
    await access(path, constants.F_OK);
  } catch {
    fail(`target repo does not exist: ${path}`);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function stripVisualizerEmitBlocks(content: string): EmitStripResult {
  const blockPattern = new RegExp(
    `\\n?[\\t ]*${escapeRegExp(EMIT_MARKER)}\\n[\\s\\S]*?\\n[\\t ]*fi\\n?`,
    "g"
  );

  let removedBlocks = 0;
  const updated = content.replace(blockPattern, () => {
    removedBlocks += 1;
    return "\n";
  });

  const normalized = updated.replace(/\n{3,}/g, "\n\n");
  return { updated: normalized, removedBlocks };
}

export function isAutoGeneratedStubContent(content: string): boolean {
  const nonEmptyLines = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  if (nonEmptyLines.length !== STUB_SCRIPT_LINES.length) {
    return false;
  }

  return STUB_SCRIPT_LINES.every((line, idx) => nonEmptyLines[idx] === line);
}

function escapeRegExp(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function matchHookFilename(filename: string, prefix?: string): HookMapping | undefined {
  const lower = basename(filename).toLowerCase();

  const direct = HOOK_MAP[lower];
  if (direct) return direct;

  if (prefix) {
    const prefixPattern = new RegExp(`^${escapeRegExp(prefix.toLowerCase())}-`);
    const stripped = lower.replace(prefixPattern, "");
    if (stripped !== lower) {
      return HOOK_MAP[stripped];
    }
  }

  return undefined;
}

async function findShellScripts(dir: string): Promise<Array<{ relPath: string; absPath: string }>> {
  const results: Array<{ relPath: string; absPath: string }> = [];

  async function walk(currentDir: string, relBase: string): Promise<void> {
    let entries: string[];
    try {
      entries = await readdir(currentDir);
    } catch {
      return;
    }

    for (const entry of entries) {
      const absEntry = join(currentDir, entry);
      const relEntry = relBase ? join(relBase, entry) : entry;
      const info = await stat(absEntry);

      if (info.isDirectory()) {
        await walk(absEntry, relEntry);
      } else if (info.isFile() && entry.endsWith(".sh")) {
        results.push({ relPath: relEntry, absPath: absEntry });
      }
    }
  }

  await walk(dir, "");
  return results;
}

async function findJsonFiles(dir: string): Promise<Array<{ relPath: string; absPath: string }>> {
  const results: Array<{ relPath: string; absPath: string }> = [];

  async function walk(currentDir: string, relBase: string): Promise<void> {
    let entries: string[];
    try {
      entries = await readdir(currentDir);
    } catch {
      return;
    }

    for (const entry of entries) {
      const absEntry = join(currentDir, entry);
      const relEntry = relBase ? join(relBase, entry) : entry;
      const info = await stat(absEntry);

      if (info.isDirectory()) {
        await walk(absEntry, relEntry);
      } else if (info.isFile() && entry.endsWith(".json")) {
        results.push({ relPath: relEntry, absPath: absEntry });
      }
    }
  }

  await walk(dir, "");
  return results;
}

function expectedHookBashPath(eventType: string, prefix?: string): string | undefined {
  const canonical = EVENT_TO_CANONICAL_HOOK[eventType];
  if (!canonical) return undefined;
  const filename = prefix ? `${prefix}-${canonical}` : canonical;
  return `./.github/hooks/${filename}`;
}

export function removeBootstrapManifestEntries(
  manifestRaw: unknown,
  prefix?: string
): ManifestRevertResult {
  if (!isRecord(manifestRaw) || !isRecord(manifestRaw.hooks)) {
    return { updated: isRecord(manifestRaw) ? { ...manifestRaw } : {}, removedEvents: [], changed: false };
  }

  const sourceHooks = manifestRaw.hooks;
  const hooks: Record<string, unknown> = { ...sourceHooks };
  const manifest: Record<string, unknown> = { ...manifestRaw, hooks };
  const removedEvents: string[] = [];
  let changed = false;

  for (const [eventType, value] of Object.entries(hooks)) {
    const expected = expectedHookBashPath(eventType, prefix);
    if (!expected || !Array.isArray(value)) {
      continue;
    }

    const commands = value as HookCommand[];
    const kept = commands.filter((cmd) => {
      if (!isRecord(cmd)) return true;
      return !(cmd.type === "command" && cmd.bash === expected);
    });

    if (kept.length !== commands.length) {
      changed = true;
      removedEvents.push(eventType);
    }

    if (kept.length === 0) {
      delete hooks[eventType];
    } else {
      hooks[eventType] = kept;
    }
  }

  manifest.hooks = hooks;
  return { updated: manifest, removedEvents, changed };
}

async function main(): Promise<void> {
  const options = parseCliArgs(process.argv.slice(2));
  if (!options) {
    console.log(usage());
    process.exit(1);
  }

  const targetRepo = resolve(options.targetRepo);
  await ensureExists(targetRepo);

  const hooksDir = join(targetRepo, ".github", "hooks");
  const vizDir = join(targetRepo, ".visualizer");

  let hooksDirExists = true;
  try {
    await access(hooksDir, constants.F_OK);
  } catch {
    hooksDirExists = false;
  }

  const scriptChanges: string[] = [];
  const deletedStubs: string[] = [];
  const manifestChanges: string[] = [];
  const skipped: string[] = [];

  if (hooksDirExists) {
    const shellScripts = await findShellScripts(hooksDir);

    for (const { relPath, absPath } of shellScripts) {
      const content = await readFile(absPath, "utf8");
      const stripped = stripVisualizerEmitBlocks(content);
      if (stripped.removedBlocks === 0) {
        continue;
      }

      const normalizedRel = relPath.replaceAll("\\", "/");
      const mapping = matchHookFilename(relPath, options.prefix);
      const canDeleteStub = Boolean(mapping) && isAutoGeneratedStubContent(stripped.updated);

      if (canDeleteStub) {
        deletedStubs.push(`.github/hooks/${normalizedRel}`);
        if (options.apply) {
          await rm(absPath, { force: true });
        }
        continue;
      }

      scriptChanges.push(`.github/hooks/${normalizedRel}`);
      if (options.apply) {
        await writeFile(absPath, stripped.updated, "utf8");
      }
    }

    const manifests = await findJsonFiles(hooksDir);
    for (const { relPath, absPath } of manifests) {
      const manifestLabel = `.github/hooks/${relPath.replaceAll("\\", "/")}`;

      // Delete the dedicated visualizer manifest entirely
      if (basename(relPath) === VISUALIZER_MANIFEST_NAME) {
        deletedStubs.push(manifestLabel);
        if (options.apply) {
          await rm(absPath, { force: true });
        }
        continue;
      }

      let parsed: unknown;
      try {
        parsed = JSON.parse(await readFile(absPath, "utf8"));
      } catch {
        skipped.push(`${manifestLabel} (invalid JSON)`);
        continue;
      }

      const reverted = removeBootstrapManifestEntries(parsed, options.prefix);
      if (!reverted.changed) {
        continue;
      }

      manifestChanges.push(`${manifestLabel}: ${reverted.removedEvents.join(", ")}`);
      if (options.apply) {
        await writeFile(absPath, `${JSON.stringify(reverted.updated, null, 2)}\n`, "utf8");
      }
    }
  }

  let visualizerExists = true;
  try {
    await access(vizDir, constants.F_OK);
  } catch {
    visualizerExists = false;
  }

  if (visualizerExists && options.apply) {
    await rm(vizDir, { recursive: true, force: true });
  }

  console.log(`\nUnbootstrap mode: ${options.apply ? "apply" : "dry-run"}`);
  console.log(`Target repo: ${targetRepo}`);
  console.log(`\nHook scripts patched: ${scriptChanges.length}`);
  for (const item of scriptChanges) {
    console.log(`  ${options.apply ? "PATCH" : "WOULD PATCH"} ${item}`);
  }

  console.log(`\nGenerated stubs deleted: ${deletedStubs.length}`);
  for (const item of deletedStubs) {
    console.log(`  ${options.apply ? "DELETE" : "WOULD DELETE"} ${item}`);
  }

  console.log(`\nManifests updated: ${manifestChanges.length}`);
  for (const item of manifestChanges) {
    console.log(`  ${options.apply ? "PATCH" : "WOULD PATCH"} ${item}`);
  }

  if (skipped.length > 0) {
    console.log(`\nSkipped: ${skipped.length}`);
    for (const item of skipped) {
      console.log(`  SKIP ${item}`);
    }
  }

  if (visualizerExists) {
    console.log(`\n${options.apply ? "DELETE" : "WOULD DELETE"} .visualizer/`);
  } else {
    console.log("\nOK .visualizer/ not present");
  }

  if (!options.apply) {
    console.log("\nDry-run only. Re-run with --apply to perform changes.");
  }
}

/* istanbul ignore next -- entry guard */
if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename ?? "")) {
  void main();
}
