import { describe, expect, it } from "vitest";
import {
  isAutoGeneratedStubContent,
  removeBootstrapManifestEntries,
  stripVisualizerEmitBlocks,
} from "../unbootstrap-existing-repo.js";

describe("stripVisualizerEmitBlocks", () => {
  it("removes the auto-wired emit block and keeps user logic", () => {
    const input = `#!/usr/bin/env bash
set -euo pipefail

echo "before"
# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
if [ -x "\${REPO_ROOT}/.visualizer/emit-event.sh" ]; then
  _VIZ_PAYLOAD={}
  "\${REPO_ROOT}/.visualizer/emit-event.sh" sessionStart "\${_VIZ_PAYLOAD}" "\${SESSION_ID}" >&2 || true
fi

echo "after"
`;

    const result = stripVisualizerEmitBlocks(input);
    expect(result.removedBlocks).toBe(1);
    expect(result.updated).toContain('echo "before"');
    expect(result.updated).toContain('echo "after"');
    expect(result.updated).not.toContain(".visualizer/emit-event.sh");
  });

  it("does nothing when no marker exists", () => {
    const input = `#!/usr/bin/env bash\necho "hello"\n`;
    const result = stripVisualizerEmitBlocks(input);
    expect(result.removedBlocks).toBe(0);
    expect(result.updated).toBe(input);
  });
});

describe("isAutoGeneratedStubContent", () => {
  it("identifies canonical generated stub content", () => {
    const content = `#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "\$SCRIPT_DIR/../.." && pwd)"

exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(true);
  });

  it("rejects stubs with custom logic", () => {
    const content = `#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Add your custom logic above the visualizer emit block below.
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "\$SCRIPT_DIR/../.." && pwd)"
echo "custom"
exit 0
`;

    expect(isAutoGeneratedStubContent(content)).toBe(false);
  });
});

describe("removeBootstrapManifestEntries", () => {
  it("removes bootstrap-managed commands and preserves unrelated entries", () => {
    const manifest = {
      version: 1,
      hooks: {
        sessionStart: [
          { type: "command", bash: "./.github/hooks/session-start.sh", cwd: ".", timeoutSec: 15 },
          { type: "command", bash: "./scripts/custom-hook.sh" },
        ],
        customEvent: [
          { type: "command", bash: "./scripts/another.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest);
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["sessionStart"]);

    const hooks = result.updated.hooks as Record<string, unknown>;
    const sessionStart = hooks.sessionStart as Array<Record<string, unknown>>;
    expect(sessionStart).toHaveLength(1);
    expect(sessionStart[0]?.bash).toBe("./scripts/custom-hook.sh");
    expect(hooks.customEvent).toBeDefined();
  });

  it("supports prefixed hook paths", () => {
    const manifest = {
      hooks: {
        subagentStart: [
          { type: "command", bash: "./.github/hooks/viz-subagent-start.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest, "viz");
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["subagentStart"]);
    expect((result.updated.hooks as Record<string, unknown>).subagentStart).toBeUndefined();
  });

  it("returns unchanged for incompatible manifest shapes", () => {
    const result = removeBootstrapManifestEntries({ version: 1 });
    expect(result.changed).toBe(false);
    expect(result.removedEvents).toEqual([]);
  });

  it("removes entries for new event types (postToolUseFailure, agentStop, notification, errorOccurred)", () => {
    const manifest = {
      version: 1,
      hooks: {
        postToolUseFailure: [
          { type: "command", bash: "./.github/hooks/post-tool-use-failure.sh" },
        ],
        agentStop: [
          { type: "command", bash: "./.github/hooks/agent-stop.sh" },
        ],
        notification: [
          { type: "command", bash: "./.github/hooks/notification.sh" },
        ],
        errorOccurred: [
          { type: "command", bash: "./.github/hooks/error-occurred.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest);
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual([
      "postToolUseFailure",
      "agentStop",
      "notification",
      "errorOccurred",
    ]);
    const hooks = result.updated.hooks as Record<string, unknown>;
    expect(hooks.postToolUseFailure).toBeUndefined();
    expect(hooks.agentStop).toBeUndefined();
    expect(hooks.notification).toBeUndefined();
    expect(hooks.errorOccurred).toBeUndefined();
  });

  it("removes prefixed entries for new event types", () => {
    const manifest = {
      hooks: {
        postToolUseFailure: [
          { type: "command", bash: "./.github/hooks/viz-post-tool-use-failure.sh" },
        ],
        errorOccurred: [
          { type: "command", bash: "./.github/hooks/viz-error-occurred.sh" },
        ],
      },
    };

    const result = removeBootstrapManifestEntries(manifest, "viz");
    expect(result.changed).toBe(true);
    expect(result.removedEvents).toEqual(["postToolUseFailure", "errorOccurred"]);
  });
});
